<!-- app/views/invoices/last.phtml -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body class="container pt-3">
<div class="container bg-primary">
    <h3>View Name: "biji"</h3>

    <p class="bg-dark text-white">I have received the parameter <?php echo $inibuah; ?></p>

</div>
    
</body>
</html>
<!-- app/views/invoices/view.phtml -->

