<!-- app/views/layouts/common.phtml -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>
<body>
<div class="container bg-success">
    <h3>ini adalah isi dari template </h3>
</div>

<div class="container">
    <?php echo $this->getContent(); ?>
</div>
    
</body>
</html>
